# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 992464f
_src_path: /home/waylon/git/pytool-template
author_github: waylonwalker
author_name: Waylon Walker
description: an animation created in pygame
package_name: pygame-animation
package_title: Pygame Animation
package_title_input: pygame animation
python_package: pygame_animation

